arrowParens: always
bracketSpacing: false
overrides:
  - files: "*.{md,yml}"
    options:
      tabWidth: 2
# required under pnp until prettier reads package.json for plugins
plugins:
  - prettier-plugin-package
printWidth: 120
proseWrap: always
tabWidth: 4
trailingComma: none
